# mkdocs.yml


site_name: Calculation Docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [/home/keith/code/MKdocs]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: false
            docstring_style: google
      watch:
        - calculator


nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md

